# Form implementation generated from reading ui file '.\UI_Forms\forms\manger_screen.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MiniSuperMarketManagement(object):
    def setupUi(self, MiniSuperMarketManagement):
        MiniSuperMarketManagement.setObjectName("MiniSuperMarketManagement")
        MiniSuperMarketManagement.resize(1280, 720)
        self.tableWidget = QtWidgets.QTableWidget(parent=MiniSuperMarketManagement)
        self.tableWidget.setGeometry(QtCore.QRect(6, 366, 1268, 348))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tableWidget.setLineWidth(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frame = QtWidgets.QFrame(parent=MiniSuperMarketManagement)
        self.frame.setGeometry(QtCore.QRect(914, 6, 360, 348))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")

        self.retranslateUi(MiniSuperMarketManagement)
        QtCore.QMetaObject.connectSlotsByName(MiniSuperMarketManagement)

    def retranslateUi(self, MiniSuperMarketManagement):
        _translate = QtCore.QCoreApplication.translate
        MiniSuperMarketManagement.setWindowTitle(_translate("MiniSuperMarketManagement", "Manger Console"))
