# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MiniSuperMarketManagement(object):
    def setupUi(self, MiniSuperMarketManagement):
        MiniSuperMarketManagement.setObjectName("MiniSuperMarketManagement")
        MiniSuperMarketManagement.resize(1280, 720)
        MiniSuperMarketManagement.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=MiniSuperMarketManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(500, 160, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 20, 221, 80))
        self.widget.setObjectName("widget")
        MiniSuperMarketManagement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MiniSuperMarketManagement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(parent=self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menutest = QtWidgets.QMenu(parent=self.menubar)
        self.menutest.setObjectName("menutest")
        MiniSuperMarketManagement.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MiniSuperMarketManagement)
        self.statusbar.setMouseTracking(False)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MiniSuperMarketManagement.setStatusBar(self.statusbar)
        self.actionLook_Up = QtGui.QAction(parent=MiniSuperMarketManagement)
        self.actionLook_Up.setObjectName("actionLook_Up")
        self.actionCalculator = QtGui.QAction(parent=MiniSuperMarketManagement)
        self.actionCalculator.setObjectName("actionCalculator")
        self.actionNew_Order = QtGui.QAction(parent=MiniSuperMarketManagement)
        self.actionNew_Order.setObjectName("actionNew_Order")
        self.actionInventory = QtGui.QAction(parent=MiniSuperMarketManagement)
        self.actionInventory.setObjectName("actionInventory")
        self.actionCustommer = QtGui.QAction(parent=MiniSuperMarketManagement)
        self.actionCustommer.setObjectName("actionCustommer")
        self.actionCustommer_2 = QtGui.QAction(parent=MiniSuperMarketManagement)
        self.actionCustommer_2.setObjectName("actionCustommer_2")
        self.actionProduct = QtGui.QAction(parent=MiniSuperMarketManagement)
        self.actionProduct.setObjectName("actionProduct")
        self.actionStaff = QtGui.QAction(parent=MiniSuperMarketManagement)
        self.actionStaff.setObjectName("actionStaff")
        self.menuTools.addAction(self.actionCalculator)
        self.menuTools.addAction(self.actionCustommer_2)
        self.menuTools.addAction(self.actionProduct)
        self.menuTools.addAction(self.actionStaff)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menutest.menuAction())

        self.retranslateUi(MiniSuperMarketManagement)
        QtCore.QMetaObject.connectSlotsByName(MiniSuperMarketManagement)

    def retranslateUi(self, MiniSuperMarketManagement):
        _translate = QtCore.QCoreApplication.translate
        MiniSuperMarketManagement.setWindowTitle(_translate("MiniSuperMarketManagement", "MiniSuperMarketManagement"))
        self.menuTools.setTitle(_translate("MiniSuperMarketManagement", "Manage"))
        self.menutest.setTitle(_translate("MiniSuperMarketManagement", "test"))
        self.actionLook_Up.setText(_translate("MiniSuperMarketManagement", "Look Up"))
        self.actionCalculator.setText(_translate("MiniSuperMarketManagement", "Order"))
        self.actionNew_Order.setText(_translate("MiniSuperMarketManagement", "New Order"))
        self.actionInventory.setText(_translate("MiniSuperMarketManagement", "New Product"))
        self.actionCustommer.setText(_translate("MiniSuperMarketManagement", "Custommer"))
        self.actionCustommer_2.setText(_translate("MiniSuperMarketManagement", "Customer"))
        self.actionProduct.setText(_translate("MiniSuperMarketManagement", "Product"))
        self.actionStaff.setText(_translate("MiniSuperMarketManagement", "Staff"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MiniSuperMarketManagement = QtWidgets.QMainWindow()
    ui = Ui_MiniSuperMarketManagement()
    ui.setupUi(MiniSuperMarketManagement)
    MiniSuperMarketManagement.show()
    sys.exit(app.exec())
