# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MiniSuperMarketManagement(object):
    def setupUi(self, MiniSuperMarketManagement):
        MiniSuperMarketManagement.setObjectName("MiniSuperMarketManagement")
        MiniSuperMarketManagement.resize(400, 300)

        self.retranslateUi(MiniSuperMarketManagement)
        QtCore.QMetaObject.connectSlotsByName(MiniSuperMarketManagement)

    def retranslateUi(self, MiniSuperMarketManagement):
        _translate = QtCore.QCoreApplication.translate
        MiniSuperMarketManagement.setWindowTitle(_translate("MiniSuperMarketManagement", "Manger Console"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MiniSuperMarketManagement = QtWidgets.QWidget()
    ui = Ui_MiniSuperMarketManagement()
    ui.setupUi(MiniSuperMarketManagement)
    MiniSuperMarketManagement.show()
    sys.exit(app.exec())
